version: "3.7"

# Configuração dos containers
services: 

  nginx-server:
    image: nginx:alpine
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/uwsgi_params:/etc/nginx/conf.d/uwsgi_params
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - web-bridge

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: openbox-ias:latest 
    container_name: discord
    volumes:
      - ./:/app
    environment:
      DB_USER: 'admin'
      DB_PASS: 'admin'
      DB_HOST: 'mysql.local'
      DB_BASE: 'discord'
      TOKEN: 'ODI0NDMwNjM5MDIwMjQ1MDAy.YFvQ3Q.SNVVxbsDaPvejbhCWPF0qTUXAVI'

    ports:
      - "3031:3031"
    networks:
      web-bridge:
        aliases:
          - uwsgi.local

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_ROOT_PASSWORD: 'root'
      POSTGRES_DATABASE: 'discord'
    ports:
      - "5432:5432"
    networks:
      web-bridge:
        aliases:
          - mysql.local
    volumes:
      - .data/postgres:/var/lib/postgres
    restart: always    
        
networks:
  web-bridge:
