# Generated by Django 3.1.7 on 2021-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210321_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='name',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
